import {
  IQ_PHONE_NUMBER_PATTERN,
  JO_PHONE_NUMBER_PATTERN,
  KW_PHONE_NUMBER_PATTERN,
  LB_PHONE_NUMBER_PATTERN,
  OM_PHONE_NUMBER_PATTERN,
  QA_PHONE_NUMBER_PATTERN,
  SA_PHONE_NUMBER_PATTERN,
  UAE_PHONE_NUMBER_PATTERN,
  YE_PHONE_NUMBER_PATTERN,
} from "./phone-numbers/asia";
import { PO_PHONE_NUMBER_PATTERN } from "./phone-numbers/europe";
import { EG_PHONE_NUMBER_PATTERN } from "./phone-numbers/africa";
import {
  MX_PHONE_NUMBER_PATTERN,
  BM_PHONE_NUMBER_PATTERN,
  CA_PHONE_NUMBER_PATTERN,
  DO_PHONE_NUMBER_PATTERN,
  USA_PHONE_NUMBER_PATTERN,
  GT_PHONE_NUMBER_PATTERN,
  HN_PHONE_NUMBER_PATTERN,
  SV_PHONE_NUMBER_PATTERN,
  CR_PHONE_NUMBER_PATTERN,
  NI_PHONE_NUMBER_PATTERN,
  BZ_PHONE_NUMBER_PATTERN,
  BS_PHONE_NUMBER_PATTERN,
  JM_PHONE_NUMBER_PATTERN,
  TT_PHONE_NUMBER_PATTERN,
  KN_PHONE_NUMBER_PATTERN,
  AG_PHONE_NUMBER_PATTERN,
  BB_PHONE_NUMBER_PATTERN,
  VC_PHONE_NUMBER_PATTERN,
  GD_PHONE_NUMBER_PATTERN,
  LC_PHONE_NUMBER_PATTERN,
  HA_PHONE_NUMBER_PATTERN,
} from "./phone-numbers/north-america";
import {
  AR_PHONE_NUMBER_PATTERN,
  BO_PHONE_NUMBER_PATTERN,
  BR_PHONE_NUMBER_PATTERN,
  CL_PHONE_NUMBER_PATTERN,
  CO_PHONE_NUMBER_PATTERN,
  EC_PHONE_NUMBER_PATTERN,
  GY_PHONE_NUMBER_PATTERN,
  PE_PHONE_NUMBER_PATTERN,
  PY_PHONE_NUMBER_PATTERN,
  SR_PHONE_NUMBER_PATTERN,
  UY_PHONE_NUMBER_PATTERN,
  VE_PHONE_NUMBER_PATTERN,
} from "./phone-numbers/south-america";

export const phoneNumbers: Map<string, RegExp> = new Map([
  // North America
  ["+1", USA_PHONE_NUMBER_PATTERN],
  ["+52", MX_PHONE_NUMBER_PATTERN],
  ["+1268", AG_PHONE_NUMBER_PATTERN],
  ["+1246", BB_PHONE_NUMBER_PATTERN],
  ["+1441", BM_PHONE_NUMBER_PATTERN],
  ["+1242", BS_PHONE_NUMBER_PATTERN],
  ["+1501", BZ_PHONE_NUMBER_PATTERN],
  ["+1", CA_PHONE_NUMBER_PATTERN],
  ["+1506", CR_PHONE_NUMBER_PATTERN],
  ["+1809", DO_PHONE_NUMBER_PATTERN],
  ["+1473", GD_PHONE_NUMBER_PATTERN],
  ["+502", GT_PHONE_NUMBER_PATTERN],
  ["+505", NI_PHONE_NUMBER_PATTERN],
  ["+509", HA_PHONE_NUMBER_PATTERN],
  ["+504", HN_PHONE_NUMBER_PATTERN],
  ["+1876", JM_PHONE_NUMBER_PATTERN],
  ["+1869", KN_PHONE_NUMBER_PATTERN],
  ["+1758", LC_PHONE_NUMBER_PATTERN],
  ["+52", MX_PHONE_NUMBER_PATTERN],
  ["+503", SV_PHONE_NUMBER_PATTERN],
  ["+1868", TT_PHONE_NUMBER_PATTERN],
  ["+1784", VC_PHONE_NUMBER_PATTERN],

  // South America

  ["+54", AR_PHONE_NUMBER_PATTERN],
  ["+591", BO_PHONE_NUMBER_PATTERN],
  ["+55", BR_PHONE_NUMBER_PATTERN],
  ["+56", CL_PHONE_NUMBER_PATTERN],
  ["+57", CO_PHONE_NUMBER_PATTERN],
  ["+593", EC_PHONE_NUMBER_PATTERN],
  ["+592", GY_PHONE_NUMBER_PATTERN],
  ["+51", PE_PHONE_NUMBER_PATTERN],
  ["+595", PY_PHONE_NUMBER_PATTERN],
  ["+597", SR_PHONE_NUMBER_PATTERN],
  ["+598", UY_PHONE_NUMBER_PATTERN],
  ["+58", VE_PHONE_NUMBER_PATTERN],

  // Europe
  ["+48", PO_PHONE_NUMBER_PATTERN],

  // Africa
  ["+961", LB_PHONE_NUMBER_PATTERN],
  ["+40", EG_PHONE_NUMBER_PATTERN],

  // Asia
  ["+964", IQ_PHONE_NUMBER_PATTERN],
  ["+966", SA_PHONE_NUMBER_PATTERN],
  ["+971", UAE_PHONE_NUMBER_PATTERN],
  ["+962", JO_PHONE_NUMBER_PATTERN],
  ["+965", KW_PHONE_NUMBER_PATTERN],
  ["+968", OM_PHONE_NUMBER_PATTERN],
  ["+974", QA_PHONE_NUMBER_PATTERN],
  ["+967", YE_PHONE_NUMBER_PATTERN],
]);
