export * from "./iq.pattern";
export * from "./jo.pattern";
export * from "./kw.pattern";
export * from "../africa/lb.pattern";
export * from "./om.pattern";
export * from "./qa.pattern";
export * from "./sa.pattern";
export * from "./uae.pattern";
export * from "./ye.pattern";
